### ISSUE TITLE
Add local tests

### ISSUE THREAD

**Issue by canyon289** [hyosubkim/bayes-toolbox#4]
Add a locall testing framework. I suggest pytest, its what most of the big packages use.

@hyosubkim any strong preference? Once we know which one to use we can get it implemented

**Comment by hyosubkim** [comment]
pytest sounds good to me. No experience with it, so will request help with implementing

**Comment by canyon289** [comment]
Great! Ill get some basic tests implemented to get things started

**Comment by hyosubkim** [comment]
@canyon289 - noob question for you: do you suggest using GitHub Actions for some of these suggestions (testing, CI, etc.)? Seems like stuff can be automatically configured from here: https://github.com/hyosubkim/bayesian-statistics-toolbox/actions/new.

**Comment by canyon289** [comment]
yes GitHub actions is great

**Comment by canyon289** [comment]
See this issue for tests in CI. 

https://github.com/hyosubkim/bayesian-statistics-toolbox/issues/6

However I would first ensure the tests work locally before worrying about CI. I can help out getting the basics in. It might take me a week or two

**Comment by hyosubkim** [comment]
Awesome. Thanks!

**Comment by hyosubkim** [comment]
I've gotten the ball rolling on some local testing with pytest [here](https://github.com/hyosubkim/bayes-toolbox/tree/main/bayes_toolbox).
