### ISSUE TITLE
Choose a documentation framework for docs

### ISSUE THREAD

**Issue by canyon289** [hyosubkim/bayes-toolbox#5]
Add a documentation framework. The two come to mind are mkdocs and sphinx. Sphinx is the most used but most heavy weight. Ive heard good things about mkdocs

https://www.sphinx-doc.org/en/master/
https://www.mkdocs.org/

**Comment by hyosubkim** [comment]
I used mkdocs to create this static site for BST: https://hyosubkim.github.io/bayesian-statistics-toolbox/. I basically copied over the content from the README.md to populate the site. Let me know what you think--thanks!

**Comment by hyosubkim** [comment]
Docs now live here: https://hyosubkim.github.io/bayes-toolbox/
